import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Textarea } from "@/components/ui/textarea";
import { trpc } from "@/lib/trpc";
import { MessageSquareText, Trophy } from "lucide-react";
import { useState } from "react";
import { toast } from "sonner";

export default function AssessmentOutcomePanels({ role }: { role: string }) {
  const results = trpc.assessments.results.useQuery(undefined, { enabled: role === "user" });
  const attempts = trpc.assessments.attempts.useQuery(undefined, { enabled: role !== "user" });
  const [feedbackByAttempt, setFeedbackByAttempt] = useState<Record<number, string>>({});
  const utils = trpc.useUtils();
  const review = trpc.assessments.review.useMutation({ onSuccess: () => { toast.success("Assessment feedback saved."); utils.assessments.attempts.invalidate(); }, onError: error => toast.error(error.message) });
  if (role === "user") return <Card className="border-[#e0e6dd]"><CardHeader><div className="flex items-center gap-3"><Trophy className="size-5 text-[#d95040]" /><div><CardTitle className="text-lg">My assessment outcomes</CardTitle><CardDescription>Scores and teacher feedback are stored with your own submitted attempts.</CardDescription></div></div></CardHeader><CardContent className="space-y-3">{results.data?.length ? results.data.map(row => <div key={row.attempt.id} className="rounded-xl border border-[#edf0eb] p-4"><div className="flex flex-wrap items-center justify-between gap-2"><div><strong className="block text-sm">{row.exam.title}</strong><span className="text-xs text-[#718077]">{row.course.code} · submitted {row.attempt.submittedAt ? new Date(row.attempt.submittedAt).toLocaleDateString() : "in progress"}</span></div><Badge className="bg-[#e2f1df] text-[#2f7452]">Score: {row.attempt.score ?? "Pending"}</Badge></div>{row.attempt.feedback && <p className="mt-3 rounded-lg bg-[#f4f7f2] p-3 text-sm leading-6 text-[#526058]">{row.attempt.feedback}</p>}</div>) : <p className="text-sm text-[#718077]">Your submitted assessment outcomes will appear here.</p>}</CardContent></Card>;
  return <Card className="border-[#e0e6dd]"><CardHeader><div className="flex items-center gap-3"><MessageSquareText className="size-5 text-[#d95040]" /><div><CardTitle className="text-lg">Assessment review</CardTitle><CardDescription>Review recorded attempt scores and add learner-visible feedback for courses you manage.</CardDescription></div></div></CardHeader><CardContent className="space-y-3">{attempts.data?.length ? attempts.data.map(row => <div key={row.attempt.id} className="rounded-xl border border-[#edf0eb] p-4"><div className="flex flex-wrap items-center justify-between gap-2"><div><strong className="block text-sm">{row.student.name || "Learner"} · {row.exam.title}</strong><span className="text-xs text-[#718077]">{row.course.code} · score {row.attempt.score ?? "Pending"}</span></div><Badge variant="secondary">{row.attempt.feedback ? "Reviewed" : "Needs feedback"}</Badge></div><Textarea className="mt-3" value={feedbackByAttempt[row.attempt.id] ?? row.attempt.feedback ?? ""} onChange={event => setFeedbackByAttempt(current => ({ ...current, [row.attempt.id]: event.target.value }))} placeholder="Write learner-facing feedback" /><Button size="sm" className="mt-2 bg-[#18201f] text-white" disabled={(feedbackByAttempt[row.attempt.id] ?? row.attempt.feedback ?? "").trim().length < 2 || review.isPending} onClick={() => review.mutate({ attemptId: row.attempt.id, feedback: feedbackByAttempt[row.attempt.id] ?? row.attempt.feedback ?? "" })}>Save feedback</Button></div>) : <p className="text-sm text-[#718077]">Submitted attempts for your courses will appear here.</p>}</CardContent></Card>;
}
