import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { trpc } from "@/lib/trpc";
import { MessageSquareText } from "lucide-react";

export default function AssessmentFeedbackAnalytics() {
  const analytics = trpc.workspace.studentAssessmentFeedbackAnalytics.useQuery();
  const max = Math.max(...(analytics.data?.trend.map(point => point.count) ?? [1]), 1);
  return <Card className="border-[#e0e6dd] bg-white"><CardHeader className="border-b border-[#edf0eb] pb-4"><div className="flex items-center justify-between gap-3"><div><CardTitle className="text-lg">Teacher feedback activity</CardTitle><CardDescription>Assessment comments recorded over the last six months.</CardDescription></div><span className="grid size-9 place-items-center rounded-xl bg-[#f1ecfb] text-[#7655a6]"><MessageSquareText className="size-4" /></span></div></CardHeader><CardContent className="pt-4">{analytics.isLoading ? <div className="h-28 animate-pulse rounded-xl bg-[#f5f2fa]" /> : analytics.data?.totalComments ? <><div className="mb-4 flex items-end gap-4"><strong className="text-3xl text-[#5d4284]">{analytics.data.totalComments}</strong><span className="pb-1 text-xs text-[#718077]">teacher comments across assessments</span></div><div className="flex h-28 items-end gap-2 border-b border-[#ece6f5] pb-5">{analytics.data.trend.map(point => <div key={point.label} className="flex min-w-0 flex-1 flex-col items-center gap-1"><span className="text-[10px] font-semibold text-[#7655a6]">{point.count || ""}</span><div className="w-full max-w-10 rounded-t-md bg-[#9c7ac7] transition-[height] duration-300 motion-reduce:transition-none" style={{ height: `${Math.max(point.count ? (point.count / max) * 68 : 4, 4)}px` }} aria-label={`${point.label}: ${point.count} comments`} /><span className="text-[10px] text-[#718077]">{point.label}</span></div>)}</div><div className="mt-4 space-y-2">{analytics.data.recent.map((comment, index) => <blockquote key={`${comment.assessmentTitle}-${index}`} className="rounded-xl border border-[#ece6f5] bg-[#fcfbfe] p-3"><p className="text-sm leading-5 text-[#4f4165]">“{comment.feedback}”</p><footer className="mt-2 text-[11px] text-[#7c708b]">{comment.courseCode} · {comment.assessmentTitle} · {new Date(comment.submittedAt).toLocaleDateString()}</footer></blockquote>)}</div></> : <div className="py-5 text-center"><MessageSquareText className="mx-auto size-5 text-[#ad9ac8]" /><strong className="mt-2 block text-sm text-[#5d4b74]">No assessment feedback yet</strong><p className="mx-auto mt-1 max-w-sm text-xs leading-5 text-[#718077]">Teacher comments added to graded assessments will appear here over time.</p></div>}</CardContent></Card>;
}
