import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { trpc } from "@/lib/trpc";
import { ArrowDown, ArrowUp, BarChart3, Bell, GripVertical, Heart } from "lucide-react";
import { useEffect, useState } from "react";
import { toast } from "sonner";

type Folder = { id: number; name: string; position: number; color: string };

function FavoriteFolderOrder() {
  const utils = trpc.useUtils();
  const folders = trpc.workspace.activityFilterPresetFavoriteFolders.useQuery();
  const [ordered, setOrdered] = useState<Folder[]>([]);
  const [draggedId, setDraggedId] = useState<number | null>(null);
  useEffect(() => { if (folders.data) setOrdered(folders.data); }, [folders.data]);
  const reorder = trpc.workspace.reorderActivityFilterPresetFavoriteFolders.useMutation({ onSuccess: () => { utils.workspace.activityFilterPresetFavoriteFolders.invalidate(); utils.workspace.sharedActivityFilterPresetTemplates.invalidate(); toast.success("Favorite folder order saved."); }, onError: error => toast.error(error.message) });
  const setColor = trpc.workspace.setActivityFilterPresetFavoriteFolderColor.useMutation({ onSuccess: () => { utils.workspace.activityFilterPresetFavoriteFolders.invalidate(); toast.success("Folder color saved."); }, onError: error => toast.error(error.message) });
  const applyOrder = (next: Folder[]) => { setOrdered(next); reorder.mutate({ folderIds: next.map(folder => folder.id) }); };
  const moveFolder = (sourceId: number, targetId: number) => { if (sourceId === targetId) return; const sourceIndex = ordered.findIndex(folder => folder.id === sourceId); const targetIndex = ordered.findIndex(folder => folder.id === targetId); if (sourceIndex < 0 || targetIndex < 0) return; const next = [...ordered]; const [item] = next.splice(sourceIndex, 1); next.splice(targetIndex, 0, item); applyOrder(next); };
  const nudgeFolder = (index: number, direction: -1 | 1) => { const target = index + direction; if (target < 0 || target >= ordered.length) return; const next = [...ordered]; [next[index], next[target]] = [next[target], next[index]]; applyOrder(next); };
  return <Card className="border-[#e0e6dd]"><CardHeader><div className="flex items-center gap-3"><span className="grid size-9 place-items-center rounded-xl bg-[#fff0f2] text-[#c4485a]"><Heart className="size-4" /></span><div><CardTitle className="text-lg">Favorite folders</CardTitle><CardDescription>Drag categories to reorder them. Arrow controls offer a keyboard alternative.</CardDescription></div></div></CardHeader><CardContent>{folders.isLoading ? <div className="h-16 animate-pulse rounded-xl bg-[#f3f6f1]" /> : ordered.length ? <div className="space-y-2" role="list" aria-label="Reorder favorite folders">{ordered.map((folder, index) => <div key={folder.id} draggable onDragStart={() => setDraggedId(folder.id)} onDragOver={event => event.preventDefault()} onDrop={() => { if (draggedId) moveFolder(draggedId, folder.id); setDraggedId(null); }} onDragEnd={() => setDraggedId(null)} className={`flex items-center gap-2 rounded-xl border p-2.5 transition-colors ${draggedId === folder.id ? "border-[#86a9cc] bg-[#edf4ff] opacity-70" : "border-[#e3eae2] bg-white"}`} role="listitem"><GripVertical className="size-4 cursor-grab text-[#7d919f] active:cursor-grabbing" aria-hidden="true" /><i className="size-3 shrink-0 rounded-full" style={{ backgroundColor: folder.color }} aria-label={`${folder.name} color`} /><strong className="min-w-0 flex-1 truncate text-sm text-[#40536b]">{folder.name}</strong><input type="color" value={folder.color} onChange={event => setColor.mutate({ folderId: folder.id, color: event.target.value })} aria-label={`Set color for ${folder.name}`} className="size-7 cursor-pointer rounded border-0 bg-transparent p-0" /><div className="flex items-center gap-1"><button type="button" disabled={index === 0 || reorder.isPending} onClick={() => nudgeFolder(index, -1)} aria-label={`Move ${folder.name} up`} className="rounded-md p-1 text-[#55705e] hover:bg-[#edf6eb] disabled:opacity-30"><ArrowUp className="size-3.5" /></button><button type="button" disabled={index === ordered.length - 1 || reorder.isPending} onClick={() => nudgeFolder(index, 1)} aria-label={`Move ${folder.name} down`} className="rounded-md p-1 text-[#55705e] hover:bg-[#edf6eb] disabled:opacity-30"><ArrowDown className="size-3.5" /></button></div></div>)}</div> : <p className="text-sm leading-6 text-[#718077]">Create a favorite folder in Recent Activities, then return here to arrange its dashboard order.</p>}</CardContent></Card>;
}

function TemplateColorFinder() {
  const folders = trpc.workspace.activityFilterPresetFavoriteFolders.useQuery();
  const templates = trpc.workspace.sharedActivityFilterPresetTemplates.useQuery();
  const [color, setColor] = useState("all");
  const matches = (templates.data ?? []).filter(template => color === "all" ? template.isFavorite : template.favoriteFolderColor === color);
  return <Card className="border-[#e0e6dd]"><CardHeader><div className="flex items-center gap-3"><span className="grid size-9 place-items-center rounded-xl bg-[#edf4ff] text-[#52749a]"><Heart className="size-4" /></span><div><CardTitle className="text-lg">Find templates by folder color</CardTitle><CardDescription>Filter your favorited shared templates using the colors assigned to your folders.</CardDescription></div></div></CardHeader><CardContent className="space-y-3"><div className="flex flex-wrap gap-2"><button type="button" onClick={() => setColor("all")} className={`rounded-full border px-2.5 py-1 text-xs ${color === "all" ? "border-[#52749a] bg-[#edf4ff] text-[#3e6892]" : "border-[#dbe5ed] bg-white text-[#6d8295]"}`}>All favorites</button>{folders.data?.map(folder => <button key={folder.id} type="button" onClick={() => setColor(folder.color)} className={`inline-flex items-center gap-1.5 rounded-full border px-2.5 py-1 text-xs ${color === folder.color ? "border-[#52749a] bg-[#edf4ff] text-[#3e6892]" : "border-[#dbe5ed] bg-white text-[#6d8295]"}`}><i className="size-2.5 rounded-full" style={{ backgroundColor: folder.color }} />{folder.name}</button>)}</div>{matches.length ? <div className="space-y-2">{matches.slice(0, 6).map(template => <div key={template.id} className="flex items-center gap-2 rounded-xl bg-[#f8fbff] p-2.5"><i className="size-2.5 rounded-full" style={{ backgroundColor: template.favoriteFolderColor ?? "#9cabbd" }} /><div className="min-w-0"><strong className="block truncate text-xs text-[#40536b]">{template.name}</strong><span className="block truncate text-[11px] text-[#718077]">{template.authorName} · {template.subject ?? "General"}</span></div></div>)}</div> : <p className="text-sm leading-6 text-[#718077]">No favorited shared templates match this folder color yet.</p>}</CardContent></Card>;
}

export default function OperationsInsights({ role }: { role: string }) {
  const notifications = trpc.notifications.list.useQuery();
  const analytics = trpc.workspace.analytics.useQuery(undefined, { enabled: role === "admin" });
  const utils = trpc.useUtils();
  const markRead = trpc.notifications.markRead.useMutation({ onSuccess: () => utils.notifications.list.invalidate(), onError: error => toast.error(error.message) });
  return <div className="grid gap-4 xl:grid-cols-2"><Card className="border-[#e0e6dd]"><CardHeader><div className="flex items-center gap-3"><span className="grid size-9 place-items-center rounded-xl bg-[#fde6e0] text-[#d95040]"><Bell className="size-4" /></span><div><CardTitle className="text-lg">Notifications</CardTitle><CardDescription>Workflow updates that belong to your authenticated account.</CardDescription></div></div></CardHeader><CardContent className="space-y-2">{notifications.data?.length ? notifications.data.slice(0, 4).map(notification => <div key={notification.id} className="flex items-start justify-between gap-3 rounded-xl border border-[#edf0eb] p-3"><div><div className="flex items-center gap-2"><strong className="text-sm">{notification.title}</strong>{!notification.readAt && <Badge className="bg-[#e2f1df] text-[#2f7452]">New</Badge>}</div><p className="mt-1 text-xs leading-5 text-[#718077]">{notification.body}</p></div>{!notification.readAt && <Button size="sm" variant="ghost" disabled={markRead.isPending} onClick={() => markRead.mutate({ notificationId: notification.id })}>Mark read</Button>}</div>) : <p className="text-sm text-[#718077]">No notifications yet. Grading and operational changes will appear here.</p>}</CardContent></Card>{role === "teacher" ? <><FavoriteFolderOrder /><TemplateColorFinder /></> : <Card className="border-[#e0e6dd]"><CardHeader><div className="flex items-center gap-3"><span className="grid size-9 place-items-center rounded-xl bg-[#e2f1df] text-[#2f7452]"><BarChart3 className="size-4" /></span><div><CardTitle className="text-lg">{role === "admin" ? "Live school signals" : "Operational signal policy"}</CardTitle><CardDescription>{role === "admin" ? "Counts are generated from persisted database records." : "School-wide metrics stay available to administrators only."}</CardDescription></div></div></CardHeader><CardContent>{role === "admin" && analytics.data ? <div className="grid grid-cols-2 gap-3 sm:grid-cols-5">{[["Students", analytics.data.students], ["Teachers", analytics.data.teachers], ["Courses", analytics.data.courses], ["Lessons", analytics.data.completedLessons], ["Submissions", analytics.data.submissions]].map(([label, value]) => <div key={label as string} className="rounded-xl bg-[#f4f7f2] p-3"><span className="block text-[10px] uppercase tracking-[.12em] text-[#718077]">{label as string}</span><strong className="mt-2 block text-xl">{value as number}</strong></div>)}</div> : <p className="text-sm leading-6 text-[#718077]">Learners and teachers see only the progress data required for their work. Administrator analytics are query-backed and scoped to the active school.</p>}</CardContent></Card>}</div>;
}
