import { Badge } from "@/components/ui/badge";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { trpc } from "@/lib/trpc";
import { History, Trash2 } from "lucide-react";

export default function RetentionRunHistory() {
  const runs = trpc.workspace.studentTrendExportRetentionRuns.useQuery();
  return <Card className="border-[#e0e6dd] bg-white"><CardHeader className="border-b border-[#edf0eb] pb-4"><div className="flex items-center justify-between gap-3"><div><CardTitle className="text-lg">Archived export cleanup history</CardTitle><CardDescription>Daily retention jobs are recorded here after they run.</CardDescription></div><span className="grid size-9 place-items-center rounded-xl bg-[#f8eadf] text-[#b76839]"><History className="size-4" /></span></div></CardHeader><CardContent className="pt-4">{runs.isLoading ? <div className="h-20 animate-pulse rounded-xl bg-[#fbf3ed]" /> : runs.data?.length ? <div className="space-y-2">{runs.data.map(run => <div key={run.id} className="flex items-center justify-between gap-3 rounded-xl border border-[#f0e6dd] bg-[#fffdfb] p-3"><div className="min-w-0"><strong className="block text-sm text-[#6b5140]">{run.status === "completed" ? "Cleanup completed" : run.status === "failed" ? "Cleanup needs attention" : "Cleanup in progress"}</strong><span className="mt-1 block text-xs text-[#887364]">{new Date(run.startedAt).toLocaleString()}</span></div><div className="flex shrink-0 items-center gap-2">{run.status === "completed" ? <span className="inline-flex items-center gap-1 text-xs font-semibold text-[#9b6036]"><Trash2 className="size-3.5" />{run.deletedCount} removed</span> : null}<Badge className={run.status === "completed" ? "bg-[#eaf4e7] text-[#397252]" : run.status === "failed" ? "bg-[#fff0f2] text-[#bd4458]" : "bg-[#fff4df] text-[#9c7429]"}>{run.status}</Badge></div></div>)}</div> : <div className="py-5 text-center"><History className="mx-auto size-5 text-[#c8a68f]" /><strong className="mt-2 block text-sm text-[#6b5140]">No cleanup runs recorded</strong><p className="mx-auto mt-1 max-w-sm text-xs leading-5 text-[#718077]">After you publish and enable daily retention, each automatic cleanup will appear here.</p></div>}</CardContent></Card>;
}
