import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { trpc } from "@/lib/trpc";
import { BarChart3, Clock3, KeyRound, Loader2, LockKeyhole, ShieldCheck } from "lucide-react";
import { useState } from "react";
import { useRoute } from "wouter";
import { useAuth } from "@/_core/hooks/useAuth";
import { startLogin } from "@/const";
import { Line, LineChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";

export default function SharedComparisonView() {
  const [, params] = useRoute("/shared/comparison/:token");
  const token = params?.token ?? "";
  const { user, loading } = useAuth();
  const [password, setPassword] = useState("");
  const [submittedPassword, setSubmittedPassword] = useState<string | undefined>();
  const shared = trpc.workspace.sharedAdminInterventionComparisonView.useQuery({ shareToken: token, password: submittedPassword }, { enabled: Boolean(token && user?.role === "admin") });
  const ready = shared.data?.status === "ready" ? shared.data : null;
  const filters = ready ? { courseId: ready.courseId ?? undefined, classSection: ready.classSection ?? undefined, startAt: ready.startAt ?? undefined, endAt: ready.endAt ?? undefined, comparisonCourseId: ready.comparisonCourseId ?? undefined, comparisonClassSection: ready.comparisonClassSection ?? undefined } : undefined;
  const analytics = trpc.workspace.interventionAnalytics.useQuery(filters, { enabled: Boolean(ready) });
  if (loading) return <div className="grid min-h-screen place-items-center bg-[#f7f5ef] text-sm text-[#66766d]"><Loader2 className="mr-2 inline size-4 animate-spin" />Checking access…</div>;
  if (!user) return <AccessCard title="Administrator sign-in required" description="This shared comparison is read-only and available only to an authenticated administrator in the same school." action="Sign in to open view" onClick={() => startLogin()} icon={<LockKeyhole className="mr-2 size-4" />} />;
  if (user.role !== "admin") return <AccessCard title="Administrator access required" description="This link cannot be opened by student or teacher accounts." />;
  if (shared.isLoading) return <div className="grid min-h-screen place-items-center bg-[#f7f5ef] text-sm text-[#66766d]"><Loader2 className="mr-2 inline size-4 animate-spin" />Loading shared comparison…</div>;
  if (shared.error || !shared.data) return <AccessCard title="Shared view unavailable" description="This link may have been revoked, belong to another school, or no longer be available." />;
  if (shared.data.status === "expired") return <AccessCard title="Shared view has expired" description="The owner set an expiry date for this read-only comparison link. Ask them to create a new link if access is still needed." icon={<Clock3 className="mr-2 size-4" />} />;
  if (shared.data.status === "password_required") return <main className="grid min-h-screen place-items-center bg-[#f7f5ef] px-5"><Card className="w-full max-w-md border-[#d9e3f3] bg-white"><CardHeader><div className="mb-2 grid size-10 place-items-center rounded-2xl bg-[#e8effc] text-[#4d70a1]"><KeyRound className="size-5" /></div><CardTitle>Password protected view</CardTitle><CardDescription>Enter the password provided by the link owner. You must also remain signed in as a same-school administrator.</CardDescription></CardHeader><CardContent className="space-y-3"><div className="space-y-1.5"><Label htmlFor="shared-view-password">Link password</Label><Input id="shared-view-password" type="password" minLength={8} maxLength={128} value={password} onChange={event => setPassword(event.target.value)} onKeyDown={event => { if (event.key === "Enter" && password.length >= 8) setSubmittedPassword(password); }} placeholder="Enter password" /></div><Button className="w-full bg-[#4f719e] text-white hover:bg-[#405f87]" disabled={password.length < 8} onClick={() => setSubmittedPassword(password)}><LockKeyhole className="mr-2 size-4" />Unlock shared view</Button><p className="text-center text-xs text-[#768596]">An incorrect password keeps the comparison settings private.</p></CardContent></Card></main>;
  if (!ready) return <AccessCard title="Shared view unavailable" description="The shared view could not be opened securely." />;
  if (analytics.isLoading) return <div className="grid min-h-screen place-items-center bg-[#f7f5ef] text-sm text-[#66766d]"><Loader2 className="mr-2 inline size-4 animate-spin" />Loading comparison data…</div>;
  if (analytics.error || !analytics.data) return <AccessCard title="Comparison data unavailable" description="The shared settings are valid, but the current comparison data could not be loaded." />;
  const chartData = analytics.data.monthlyTrend.map((month, index) => ({ month: month.month, primary: month.completedLessons, comparison: analytics.data.cohortComparison?.monthlyTrend[index]?.completedLessons ?? null }));
  return <main className="min-h-screen bg-[#f7f5ef] p-5 text-[#1d2823] md:p-9"><div className="mx-auto max-w-5xl space-y-5"><Card className="border-[#d9e3f3] bg-[linear-gradient(135deg,#f7faff_0%,#ffffff_70%)]"><CardHeader><div className="flex flex-wrap items-start justify-between gap-3"><div><div className="mb-2 inline-flex items-center gap-2 rounded-full bg-[#e8effc] px-2.5 py-1 text-[10px] font-bold uppercase tracking-[.12em] text-[#4e6f9d]"><ShieldCheck className="size-3" />Read-only shared view</div><CardTitle>{ready.name}</CardTitle><CardDescription>Saved by another administrator in your school. These settings cannot be changed from this link.</CardDescription></div><span className="grid size-10 place-items-center rounded-2xl bg-[#e5edfc] text-[#5073a3]"><BarChart3 className="size-5" /></span></div></CardHeader><CardContent className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><Info label="Primary cohort" value={ready.courseId ? `Course #${ready.courseId}` : ready.classSection || "All courses"} /><Info label="Comparison cohort" value={ready.comparisonCourseId ? `Course #${ready.comparisonCourseId}` : ready.comparisonClassSection || "Not selected"} /><Info label="Date range" value={`${ready.startAt ? new Date(ready.startAt).toLocaleDateString() : "Default"} — ${ready.endAt ? new Date(ready.endAt).toLocaleDateString() : "Current"}`} /><Info label="Display mode" value={ready.normalized ? "Normalized comparison" : "Raw counts"} /></CardContent></Card><Card className="border-[#dfe7f2] bg-white"><CardHeader><CardTitle className="text-lg">Completed lesson trend</CardTitle><CardDescription>Current school-scoped intervention data loaded against the shared comparison settings.</CardDescription></CardHeader><CardContent><div className="h-80"><ResponsiveContainer width="100%" height="100%"><LineChart data={chartData}><XAxis dataKey="month" /><YAxis /><Tooltip /><Line type="monotone" dataKey="primary" name="Primary completed lessons" stroke="#5b9b74" strokeWidth={2.5} dot={{ r: 3 }} />{analytics.data.cohortComparison ? <Line type="monotone" dataKey="comparison" name="Comparison completed lessons" stroke="#5978aa" strokeWidth={2.5} strokeDasharray="5 4" dot={{ r: 3 }} /> : null}</LineChart></ResponsiveContainer></div></CardContent></Card></div></main>;
}

function Info({ label, value }: { label: string; value: string }) { return <div className="rounded-xl border border-[#e2e9f3] bg-white p-3"><span className="text-[10px] font-bold uppercase tracking-[.1em] text-[#728299]">{label}</span><strong className="mt-2 block text-sm">{value}</strong></div>; }
function AccessCard({ title, description, action, onClick, icon }: { title: string; description: string; action?: string; onClick?: () => void; icon?: React.ReactNode }) { return <div className="grid min-h-screen place-items-center bg-[#f7f5ef] px-5"><Card className="max-w-md border-[#d9e3f3] bg-white"><CardHeader><CardTitle>{title}</CardTitle><CardDescription>{description}</CardDescription></CardHeader>{action ? <CardContent><Button className="w-full bg-[#4f719e] text-white" onClick={onClick}>{icon}{action}</Button></CardContent> : null}</Card></div>; }
