import { Badge } from "@/components/ui/badge";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { trpc } from "@/lib/trpc";
import { BarChart3, GraduationCap } from "lucide-react";
import WeeklyProgressTrend from "./WeeklyProgressTrend";
import ExportRetentionSettings from "./ExportRetentionSettings";
import AssessmentFeedbackAnalytics from "./AssessmentFeedbackAnalytics";
import RetentionRunHistory from "./RetentionRunHistory";
import StudentEngagement from "./StudentEngagement";

export default function StudentProgress() {
  const progress = trpc.workspace.studentProgress.useQuery();
  if (progress.isLoading) return <Card className="border-[#e0e6dd]"><CardContent className="space-y-4 p-5"><div className="h-5 w-40 animate-pulse rounded bg-[#edf2eb]" /><div className="h-36 animate-pulse rounded-xl bg-[#f3f6f1]" /></CardContent></Card>;
  if (!progress.data?.length) return <div className="space-y-4"><Card className="border-[#e0e6dd] bg-white"><CardHeader><CardTitle className="text-lg">Learning progress</CardTitle><CardDescription>Completion and assessment performance are shown course by course.</CardDescription></CardHeader><CardContent className="py-8 text-center"><GraduationCap className="mx-auto size-6 text-[#82a589]" /><strong className="mt-3 block text-sm">Your progress chart is ready</strong><p className="mx-auto mt-1 max-w-sm text-xs leading-5 text-[#718077]">Enroll in a published course and complete lessons or assessments to populate this view.</p></CardContent></Card><StudentEngagement /></div>;
  return <div className="space-y-4"><Card className="overflow-hidden border-[#e0e6dd] bg-white"><CardHeader className="flex flex-row items-center justify-between space-y-0 border-b border-[#edf0eb] pb-4"><div><CardTitle className="text-lg">Learning progress</CardTitle><CardDescription>Course completion and assessment performance.</CardDescription></div><span className="grid size-9 place-items-center rounded-xl bg-[#e2f1df] text-[#2f7452]"><BarChart3 className="size-4" /></span></CardHeader><CardContent className="space-y-5 pt-5">{progress.data.map(row => <div key={row.courseId} className="rounded-xl border border-[#e5ebe2] bg-[#fbfcfa] p-4"><div className="flex flex-wrap items-start justify-between gap-2"><div><strong className="block text-sm">{row.title}</strong><span className="mt-1 block text-xs text-[#718077]">{row.code} · {row.subject} · {row.classSection}</span></div><Badge className="bg-[#edf5ea] text-[#337153] hover:bg-[#edf5ea]">{row.completionPercent}% complete</Badge></div><div className="mt-4 grid gap-4 sm:grid-cols-2"><div><div className="mb-2 flex justify-between text-xs"><span className="text-[#617067]">Course completion</span><strong>{row.completed}/{row.total} lessons</strong></div><div className="h-2.5 overflow-hidden rounded-full bg-[#e4ece1]"><div className="h-full rounded-full bg-[#5aa878] transition-[width] duration-500 ease-out motion-reduce:transition-none" style={{ width: `${row.completionPercent}%` }} /></div></div><div><div className="mb-2 flex justify-between text-xs"><span className="text-[#617067]">Assessment performance</span><strong>{row.performancePercent}%</strong></div><div className="h-2.5 overflow-hidden rounded-full bg-[#f1e5dc]"><div className="h-full rounded-full bg-[#e7795b] transition-[width] duration-500 ease-out motion-reduce:transition-none" style={{ width: `${row.performancePercent}%` }} /></div></div></div></div>)}</CardContent></Card><StudentEngagement /><WeeklyProgressTrend /><AssessmentFeedbackAnalytics /><ExportRetentionSettings /><RetentionRunHistory /></div>;
}
