import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { trpc } from "@/lib/trpc";
import { ClipboardX, Loader2, MessageSquareText, Send, UserRoundCheck } from "lucide-react";
import { toast } from "sonner";

export default function TeacherRejectionFeedbackHistory() {
  const utils = trpc.useUtils();
  const history = trpc.workspace.teacherRejectionFeedbackHistory.useQuery();
  const resubmit = trpc.workspace.setTeacherReminderTemplateShared.useMutation({ onSuccess: () => { utils.workspace.teacherReminderTemplates.invalidate(); utils.workspace.teacherRejectionFeedbackHistory.invalidate(); utils.workspace.reminderTemplateApprovalQueue.invalidate(); toast.success("Template resubmitted for administrator review."); }, onError: error => toast.error(error.message) });
  return <Card className="border-[#f0dfd7] bg-[linear-gradient(135deg,#fffaf8_0%,#ffffff_76%)]"><CardHeader className="border-b border-[#f2e5e0]"><div className="flex items-start justify-between gap-3"><div><div className="mb-2 inline-flex items-center gap-2 rounded-full bg-[#fff0eb] px-2.5 py-1 text-[10px] font-bold uppercase tracking-[.12em] text-[#a45340]"><MessageSquareText className="size-3" />Template improvement history</div><CardTitle className="text-lg">Administrator feedback</CardTitle><CardDescription>Review prior comments and resubmit the same saved template directly when your edits are ready.</CardDescription></div><span className="grid size-10 place-items-center rounded-2xl bg-[#fde8e1] text-[#aa5542]"><ClipboardX className="size-5" /></span></div></CardHeader><CardContent className="pt-4">{history.isLoading ? <div className="h-28 animate-pulse rounded-xl bg-[#fff0eb]" /> : history.data?.length ? <div className="space-y-3">{history.data.map(item => <article key={item.id} className="rounded-xl border border-[#f0dfd8] bg-white/85 p-3"><div className="flex flex-wrap items-start justify-between gap-2"><div className="min-w-0"><strong className="block truncate text-sm text-[#894636]">{item.name}</strong><span className="mt-1 block text-[11px] text-[#977a71]">Reviewed {item.reviewedAt ? new Date(item.reviewedAt).toLocaleString() : "recently"}</span></div><Badge className="bg-[#fff0eb] text-[#a45340]">Needs edits</Badge></div><div className="mt-3 rounded-lg border border-[#f4e1db] bg-[#fff8f5] p-2.5"><span className="text-[10px] font-bold uppercase tracking-[.1em] text-[#a66c5d]">Administrator feedback</span><p className="mt-1 text-xs leading-5 text-[#784f44]">{item.reviewNote || "No feedback comment was recorded."}</p></div><div className="mt-3 flex flex-wrap items-center justify-between gap-2"><span className="inline-flex items-center gap-1.5 text-[11px] text-[#8a756e]"><UserRoundCheck className="size-3.5" />{item.reviewer?.name || item.reviewer?.email || "Administrator"}</span><Button size="sm" disabled={resubmit.isPending} className="bg-[#a65441] text-white hover:bg-[#8d4535]" onClick={() => resubmit.mutate({ templateId: item.id, isShared: true })}>{resubmit.isPending ? <Loader2 className="mr-1.5 size-3.5 animate-spin" /> : <Send className="mr-1.5 size-3.5" />}{resubmit.isPending ? "Resubmitting…" : "Resubmit for review"}</Button></div></article>)}</div> : <div className="rounded-xl border border-dashed border-[#edddd6] bg-white/75 p-7 text-center"><ClipboardX className="mx-auto size-5 text-[#c28777]" /><strong className="mt-2 block text-sm text-[#8b5548]">No past feedback to review</strong><p className="mx-auto mt-1 max-w-sm text-xs leading-5 text-[#93776e]">If an administrator requests changes to a submitted reminder template, the feedback will remain available here.</p></div>}</CardContent></Card>;
}
