import { TRPCError } from "@trpc/server";
import { z } from "zod";
import { parse as parseCookie } from "cookie";
import { COOKIE_NAME } from "../shared/const";
import {
  createAiRun,
  createActivityFilterPresetFavoriteFolder,
  createStudentTrendExport,
  bulkArchiveStudentTrendExports,
  bulkDeleteStudentTrendExports,
  bulkRestoreStudentTrendExports,
  copySharedActivityFilterPresetTemplate,
  deleteActivityFilterPreset,
  createAssignment,
  createBackupJob,
  createSchoolInvite,
  createStudentAchievementCertificate,
  createConversation,
  createCourse,
  createExam,
  createNotification,
  createSchoolInterventionExport,
  generateStudyPlan,
  createLesson,
  createModule,
  createScheduleEvent,
  acceptSchoolInvite,
  enrollStudent,
  getCourseDetail,
  getDashboard,
  getExamForAttempt,
  getSchoolAnalytics,
  getSchoolInterventionAnalytics,
  getNotificationInbox,
  getNotificationPreferences,
  getStudentAssessmentFeedbackAnalytics,
  getStudentEngagementSummary,
  getStudentLearningFocus,
  getTeacherLearnerAttention,
  getTrendExportRetentionPolicy,
  getStudentProgress,
  getStudentWeeklyTrend,
  getWorkspace,
  gradeSubmission,
  initializeWorkspace,
  listAssignments,
  listAuditLogs,
  listBackupJobs,
  listMyAcceptedAiRuns,
  listPendingAiRuns,
  listReportExports,
  listRecentActivities,
  listActivityFilterPresets,
  listActivityFilterPresetFavoriteFolders,
  listStudentTrendExportHistory,
  listStudentTrendExportRetentionRuns,
  listSharedActivityFilterPresetTemplates,
  listConversations,
  listCoursesForUser,
  listExams,
  listMyAssessmentResults,
  listAssessmentAttemptsForReview,
  listMessages,
  listMistakes,
  listNotifications,
  listSentNotifications,
  listSchedule,
  listSchoolInvites,
  listSubmissionsForTeacher,
  listUsers,
  markNotificationRead,
  publishCourse,
  requestReportExport,
  revokeSchoolInvite,
  revokeStudentAchievementCertificate,
  resetDefaultActivityFilterPreset,
  deleteActivityFilterPresetFavoriteFolder,
  assignActivityFilterPresetFavoriteFolder,
  setActivityFilterPresetFavoriteFolderColor,
  reorderActivityFilterPresetFavoriteFolders,
  reviewAiRun,
  reviewAssessmentAttempt,
  saveMistake,
  saveActivityFilterPreset,
  setActivityFilterPresetShared,
  setActivityFilterPresetFavorite,
  setDefaultActivityFilterPreset,
  addExamQuestion,
  setLessonProgress,
  sendMessage,
  sendTeacherBulkLearningReminder,
  submitExamAttempt,
  submitAssignment,
  updateProfileRole,
  updateNotificationPreferences,
  updateTrendExportRetentionPolicy,
  verifyStudentAchievementCertificate,
  createTeacherReminderTemplate,
  deleteTeacherReminderTemplate,
  listTeacherReminderTemplates,
  setTeacherReminderTemplateShared,
  listSchoolReminderTemplateLibrary,
  copySchoolReminderTemplate,
  listCertificateRevocationAudit,
  revokeCertificateForAdmin,
  listReminderTemplateApprovalQueue,
  reviewReminderTemplateSubmission,
  listAdminInterventionComparisonViews,
  createAdminInterventionComparisonView,
  deleteAdminInterventionComparisonView,
  createCertificateRevocationAuditExport,
  setAdminInterventionComparisonViewSharing,
  getSharedAdminInterventionComparisonView,
  getMonthlyCertificateAuditReportSchedule,
  updateMonthlyCertificateAuditReportSchedule,
  getMonthlyComparisonReviewSchedule,
  updateMonthlyComparisonReviewSchedule,
  listTeacherRejectionFeedbackHistory,
  listAdminComparisonSharingActivity,
  getAdminComparisonSharingAuditSummary,
  createAdminComparisonSharingAuditExport,
  listAdminComparisonSharingAuditExports,
  setAdminComparisonSharingAuditExportArchived,
  getComparisonSharingExportRetentionPolicy,
  updateComparisonSharingExportRetentionPolicy,
  listComparisonSharingExportRetentionRuns,
} from "./db";
import { getSessionCookieOptions } from "./_core/cookies";
import { adminProcedure, protectedProcedure, publicProcedure, router } from "./_core/trpc";
import { systemRouter } from "./_core/systemRouter";

const teacherProcedure = protectedProcedure.use(({ ctx, next }) => {
  if (!ctx.user || !["teacher", "admin"].includes(ctx.user.role)) throw new TRPCError({ code: "FORBIDDEN", message: "Teacher or administrator access is required." });
  return next({ ctx: { ...ctx, user: ctx.user } });
});

function requestOrigin(req: { protocol?: string; headers: Record<string, string | string[] | undefined> }) {
  const forwardedHost = req.headers["x-forwarded-host"] ?? req.headers.host;
  const host = Array.isArray(forwardedHost) ? forwardedHost[0] : forwardedHost;
  const forwardedProtocol = req.headers["x-forwarded-proto"];
  const protocol = (Array.isArray(forwardedProtocol) ? forwardedProtocol[0] : forwardedProtocol) || req.protocol || "https";
  return host ? `${protocol}://${host}` : "https://educonnect.local";
}

const interventionAnalyticsShape = z.object({
  courseId: z.number().int().positive().optional(),
  classSection: z.string().trim().min(1).max(120).optional(),
  startAt: z.date().optional(),
  endAt: z.date().optional(),
  comparisonCourseId: z.number().int().positive().optional(),
  comparisonClassSection: z.string().trim().min(1).max(120).optional(),
});
const interventionAnalyticsInput = interventionAnalyticsShape.refine(input => !input.startAt || !input.endAt || (input.startAt <= input.endAt && input.endAt.getTime() - input.startAt.getTime() <= 366 * 86_400_000), { message: "Choose a valid date range of up to one year." });
const savedInterventionViewInput = interventionAnalyticsShape.extend({ name: z.string().trim().min(1).max(80), normalized: z.boolean() }).refine(input => !input.startAt || !input.endAt || (input.startAt <= input.endAt && input.endAt.getTime() - input.startAt.getTime() <= 366 * 86_400_000), { message: "Choose a valid date range of up to one year." });
const certificateRevocationAuditInput = z.object({ studentSearch: z.string().trim().min(1).max(120).optional(), milestoneId: z.string().trim().min(1).max(64).optional(), actorRole: z.enum(["student", "administrator"]).optional(), startAt: z.date().optional(), endAt: z.date().optional() }).refine(input => !input.startAt || !input.endAt || input.startAt <= input.endAt, { message: "Start date must be before end date." });

export const appRouter = router({
  system: systemRouter,
  auth: router({
    me: publicProcedure.query(({ ctx }) => ctx.user),
    logout: publicProcedure.mutation(({ ctx }) => {
      ctx.res.clearCookie(COOKIE_NAME, { ...getSessionCookieOptions(ctx.req), maxAge: -1 });
      return { success: true } as const;
    }),
  }),
  workspace: router({
    me: protectedProcedure.query(({ ctx }) => getWorkspace(ctx.user.id)),
    initialize: adminProcedure.input(z.object({ schoolName: z.string().min(2).max(180) })).mutation(({ ctx, input }) => initializeWorkspace(ctx.user.id, input.schoolName)),
    createInvite: adminProcedure.input(z.object({ role: z.enum(["user", "teacher", "admin"]) })).mutation(({ ctx, input }) => createSchoolInvite(ctx.user.id, input.role)),
    invites: adminProcedure.query(({ ctx }) => listSchoolInvites(ctx.user.id)),
    revokeInvite: adminProcedure.input(z.object({ inviteId: z.number().int().positive() })).mutation(({ ctx, input }) => revokeSchoolInvite(ctx.user.id, input.inviteId)),
    acceptInvite: protectedProcedure.input(z.object({ code: z.string().min(12).max(48) })).mutation(({ ctx, input }) => acceptSchoolInvite(ctx.user.id, input.code)),
    users: adminProcedure.query(({ ctx }) => getWorkspace(ctx.user.id).then(({ user }) => user.schoolId ? listUsers(user.schoolId) : [])),
    members: protectedProcedure.query(({ ctx }) => getWorkspace(ctx.user.id).then(({ user }) => user.schoolId ? listUsers(user.schoolId) : [])),
    setRole: adminProcedure.input(z.object({ userId: z.number().int().positive(), role: z.enum(["user", "teacher", "admin"]) })).mutation(({ ctx, input }) => updateProfileRole(ctx.user.id, input.userId, input.role)),
    dashboard: protectedProcedure.query(({ ctx }) => getDashboard(ctx.user.id)),
    recentActivities: protectedProcedure.input(z.object({ courseId: z.number().int().positive().optional(), subject: z.string().max(120).optional(), classSection: z.string().max(120).optional(), startAt: z.date().optional(), endAt: z.date().optional() }).refine(input => !input.startAt || !input.endAt || input.startAt <= input.endAt, { message: "Start date must be before end date." }).optional()).query(({ ctx, input }) => listRecentActivities(ctx.user.id, input)),
    studentProgress: protectedProcedure.query(({ ctx }) => getStudentProgress(ctx.user.id)),
    studentWeeklyTrend: protectedProcedure.input(z.object({ weeks: z.union([z.literal(4), z.literal(8), z.literal(12)]).default(4) }).optional()).query(({ ctx, input }) => getStudentWeeklyTrend(ctx.user.id, input?.weeks ?? 4)),
    studentAssessmentFeedbackAnalytics: protectedProcedure.query(({ ctx }) => getStudentAssessmentFeedbackAnalytics(ctx.user.id)),
    studentEngagementSummary: protectedProcedure.query(({ ctx }) => getStudentEngagementSummary(ctx.user.id)),
    createStudentAchievementCertificate: protectedProcedure.input(z.object({ milestoneId: z.string().trim().min(3).max(64) })).mutation(({ ctx, input }) => createStudentAchievementCertificate(ctx.user.id, input.milestoneId, requestOrigin(ctx.req))),
    revokeStudentAchievementCertificate: protectedProcedure.input(z.object({ milestoneId: z.string().trim().min(3).max(64), reason: z.string().trim().min(1).max(300).optional() })).mutation(({ ctx, input }) => revokeStudentAchievementCertificate(ctx.user.id, input.milestoneId, input.reason)),
    verifyAchievementCertificate: publicProcedure.input(z.object({ verificationToken: z.string().trim().min(20).max(96) })).query(({ input }) => verifyStudentAchievementCertificate(input.verificationToken)),
    studentLearningFocus: protectedProcedure.query(({ ctx }) => getStudentLearningFocus(ctx.user.id)),
    teacherLearnerAttention: teacherProcedure.query(({ ctx }) => getTeacherLearnerAttention(ctx.user.id)),
    sendTeacherBulkLearningReminder: teacherProcedure.input(z.object({ target: z.enum(["pending_tasks", "low_progress", "all"]), personalNote: z.string().trim().min(1).max(500).optional() })).mutation(({ ctx, input }) => sendTeacherBulkLearningReminder(ctx.user.id, input.target, input.personalNote)),
    teacherReminderTemplates: teacherProcedure.query(({ ctx }) => listTeacherReminderTemplates(ctx.user.id)),
    createTeacherReminderTemplate: teacherProcedure.input(z.object({ name: z.string().trim().min(1).max(80), note: z.string().trim().min(1).max(500) })).mutation(({ ctx, input }) => createTeacherReminderTemplate(ctx.user.id, input)),
    deleteTeacherReminderTemplate: teacherProcedure.input(z.object({ templateId: z.number().int().positive() })).mutation(({ ctx, input }) => deleteTeacherReminderTemplate(ctx.user.id, input.templateId)),
    setTeacherReminderTemplateShared: teacherProcedure.input(z.object({ templateId: z.number().int().positive(), isShared: z.boolean() })).mutation(({ ctx, input }) => setTeacherReminderTemplateShared(ctx.user.id, input.templateId, input.isShared)),
    teacherRejectionFeedbackHistory: teacherProcedure.query(({ ctx }) => listTeacherRejectionFeedbackHistory(ctx.user.id)),
    schoolReminderTemplateLibrary: teacherProcedure.query(({ ctx }) => listSchoolReminderTemplateLibrary(ctx.user.id)),
    copySchoolReminderTemplate: teacherProcedure.input(z.object({ templateId: z.number().int().positive(), name: z.string().trim().min(1).max(80) })).mutation(({ ctx, input }) => copySchoolReminderTemplate(ctx.user.id, input.templateId, input.name)),
    activityFilterPresets: teacherProcedure.query(({ ctx }) => listActivityFilterPresets(ctx.user.id)),
    saveActivityFilterPreset: teacherProcedure.input(z.object({ name: z.string().trim().min(1).max(80), courseId: z.number().int().positive().optional(), subject: z.string().max(120).optional(), classSection: z.string().max(120).optional(), startDate: z.string().regex(/^\d{4}-\d{2}-\d{2}$/).optional(), endDate: z.string().regex(/^\d{4}-\d{2}-\d{2}$/).optional(), tags: z.array(z.string().trim().min(1).max(32)).max(8).optional() }).refine(input => !input.startDate || !input.endDate || input.startDate <= input.endDate, { message: "Start date must be before end date." })).mutation(({ ctx, input }) => saveActivityFilterPreset(ctx.user.id, input)),
    deleteActivityFilterPreset: teacherProcedure.input(z.object({ presetId: z.number().int().positive() })).mutation(({ ctx, input }) => deleteActivityFilterPreset(ctx.user.id, input.presetId)),
    setDefaultActivityFilterPreset: teacherProcedure.input(z.object({ presetId: z.number().int().positive() })).mutation(({ ctx, input }) => setDefaultActivityFilterPreset(ctx.user.id, input.presetId)),
    resetDefaultActivityFilterPreset: teacherProcedure.mutation(({ ctx }) => resetDefaultActivityFilterPreset(ctx.user.id)),
    setActivityFilterPresetShared: teacherProcedure.input(z.object({ presetId: z.number().int().positive(), isShared: z.boolean() })).mutation(({ ctx, input }) => setActivityFilterPresetShared(ctx.user.id, input.presetId, input.isShared)),
    setActivityFilterPresetFavorite: teacherProcedure.input(z.object({ presetId: z.number().int().positive(), isFavorite: z.boolean() })).mutation(({ ctx, input }) => setActivityFilterPresetFavorite(ctx.user.id, input.presetId, input.isFavorite)),
    activityFilterPresetFavoriteFolders: teacherProcedure.query(({ ctx }) => listActivityFilterPresetFavoriteFolders(ctx.user.id)),
    createActivityFilterPresetFavoriteFolder: teacherProcedure.input(z.object({ name: z.string().trim().min(1).max(60), color: z.string().regex(/^#[0-9a-fA-F]{6}$/).optional() })).mutation(({ ctx, input }) => createActivityFilterPresetFavoriteFolder(ctx.user.id, input.name, input.color)),
    deleteActivityFilterPresetFavoriteFolder: teacherProcedure.input(z.object({ folderId: z.number().int().positive() })).mutation(({ ctx, input }) => deleteActivityFilterPresetFavoriteFolder(ctx.user.id, input.folderId)),
    setActivityFilterPresetFavoriteFolderColor: teacherProcedure.input(z.object({ folderId: z.number().int().positive(), color: z.string().regex(/^#[0-9a-fA-F]{6}$/) })).mutation(({ ctx, input }) => setActivityFilterPresetFavoriteFolderColor(ctx.user.id, input.folderId, input.color)),
    assignActivityFilterPresetFavoriteFolder: teacherProcedure.input(z.object({ presetId: z.number().int().positive(), folderId: z.number().int().positive().optional() })).mutation(({ ctx, input }) => assignActivityFilterPresetFavoriteFolder(ctx.user.id, input.presetId, input.folderId)),
    reorderActivityFilterPresetFavoriteFolders: teacherProcedure.input(z.object({ folderIds: z.array(z.number().int().positive()).min(1).max(50) })).mutation(({ ctx, input }) => reorderActivityFilterPresetFavoriteFolders(ctx.user.id, input.folderIds)),
    sharedActivityFilterPresetTemplates: teacherProcedure.query(({ ctx }) => listSharedActivityFilterPresetTemplates(ctx.user.id)),
    copySharedActivityFilterPresetTemplate: teacherProcedure.input(z.object({ templateId: z.number().int().positive(), name: z.string().trim().min(1).max(80) })).mutation(({ ctx, input }) => copySharedActivityFilterPresetTemplate(ctx.user.id, input.templateId, input.name)),
    studentTrendExportHistory: protectedProcedure.input(z.object({ cursor: z.number().int().positive().optional(), weekCount: z.union([z.literal(4), z.literal(8), z.literal(12)]).optional(), startAt: z.date().optional(), endAt: z.date().optional(), includeArchived: z.boolean().optional(), limit: z.number().int().min(1).max(25).optional() }).refine(input => !input.startAt || !input.endAt || input.startAt <= input.endAt, { message: "Start date must be before end date." }).optional()).query(({ ctx, input }) => listStudentTrendExportHistory(ctx.user.id, input)),
    createStudentTrendExport: protectedProcedure.input(z.object({ weeks: z.union([z.literal(4), z.literal(8), z.literal(12)]) })).mutation(({ ctx, input }) => createStudentTrendExport(ctx.user.id, input.weeks)),
    bulkArchiveStudentTrendExports: protectedProcedure.input(z.object({ exportIds: z.array(z.number().int().positive()).min(1).max(50) })).mutation(({ ctx, input }) => bulkArchiveStudentTrendExports(ctx.user.id, input.exportIds)),
    bulkDeleteStudentTrendExports: protectedProcedure.input(z.object({ exportIds: z.array(z.number().int().positive()).min(1).max(50) })).mutation(({ ctx, input }) => bulkDeleteStudentTrendExports(ctx.user.id, input.exportIds)),
    bulkRestoreStudentTrendExports: protectedProcedure.input(z.object({ exportIds: z.array(z.number().int().positive()).min(1).max(50) })).mutation(({ ctx, input }) => bulkRestoreStudentTrendExports(ctx.user.id, input.exportIds)),
    studentTrendExportRetention: protectedProcedure.query(({ ctx }) => getTrendExportRetentionPolicy(ctx.user.id)),
    updateStudentTrendExportRetention: protectedProcedure.input(z.object({ enabled: z.boolean(), retentionDays: z.union([z.literal(0), z.literal(7), z.literal(30), z.literal(60), z.literal(90), z.literal(180)]) })).mutation(({ ctx, input }) => updateTrendExportRetentionPolicy(ctx.user.id, input, parseCookie(ctx.req.headers.cookie ?? "")[COOKIE_NAME] ?? "")),
    studentTrendExportRetentionRuns: protectedProcedure.query(({ ctx }) => listStudentTrendExportRetentionRuns(ctx.user.id)),
    auditLogs: adminProcedure.query(({ ctx }) => listAuditLogs(ctx.user.id)),
    certificateRevocationAudit: adminProcedure.input(certificateRevocationAuditInput.optional()).query(({ ctx, input }) => listCertificateRevocationAudit(ctx.user.id, input)),
    exportCertificateRevocationAudit: adminProcedure.input(certificateRevocationAuditInput.optional()).mutation(({ ctx, input }) => createCertificateRevocationAuditExport(ctx.user.id, input)),
    revokeCertificateForAdmin: adminProcedure.input(z.object({ certificateId: z.number().int().positive(), reason: z.string().trim().min(3).max(300) })).mutation(({ ctx, input }) => revokeCertificateForAdmin(ctx.user.id, input.certificateId, input.reason)),
    reminderTemplateApprovalQueue: adminProcedure.query(({ ctx }) => listReminderTemplateApprovalQueue(ctx.user.id)),
    reviewReminderTemplateSubmission: adminProcedure.input(z.object({ templateId: z.number().int().positive(), approved: z.boolean(), reviewNote: z.string().trim().max(300).optional() }).refine(input => input.approved || Boolean(input.reviewNote && input.reviewNote.length >= 3), { message: "A feedback comment of at least 3 characters is required when rejecting a template.", path: ["reviewNote"] })).mutation(({ ctx, input }) => reviewReminderTemplateSubmission(ctx.user.id, input.templateId, input.approved, input.reviewNote)),
    adminInterventionComparisonViews: adminProcedure.query(({ ctx }) => listAdminInterventionComparisonViews(ctx.user.id)),
    createAdminInterventionComparisonView: adminProcedure.input(savedInterventionViewInput).mutation(({ ctx, input }) => createAdminInterventionComparisonView(ctx.user.id, input)),
    deleteAdminInterventionComparisonView: adminProcedure.input(z.object({ viewId: z.number().int().positive() })).mutation(({ ctx, input }) => deleteAdminInterventionComparisonView(ctx.user.id, input.viewId)),
    setAdminInterventionComparisonViewSharing: adminProcedure.input(z.object({ viewId: z.number().int().positive(), share: z.boolean(), expiresAt: z.date().optional(), password: z.string().min(8).max(128).optional() }).refine(input => !input.expiresAt || input.expiresAt > new Date(), { message: "Share expiry must be in the future.", path: ["expiresAt"] })).mutation(({ ctx, input }) => setAdminInterventionComparisonViewSharing(ctx.user.id, input.viewId, input.share, { expiresAt: input.expiresAt, password: input.password })),
    sharedAdminInterventionComparisonView: adminProcedure.input(z.object({ shareToken: z.string().trim().min(24).max(96), password: z.string().max(128).optional() })).query(({ ctx, input }) => getSharedAdminInterventionComparisonView(ctx.user.id, input.shareToken, input.password)),
    adminComparisonSharingActivity: adminProcedure.input(z.object({ ownerId: z.number().int().positive().optional(), action: z.enum(["shared", "revoked", "auto_revoked"]).optional(), startAt: z.date().optional(), endAt: z.date().optional() }).refine(input => !input.startAt || !input.endAt || input.startAt <= input.endAt, { message: "Start date must be before end date." }).optional()).query(({ ctx, input }) => listAdminComparisonSharingActivity(ctx.user.id, input)),
    adminComparisonSharingAuditSummary: adminProcedure.input(z.object({ ownerId: z.number().int().positive().optional(), action: z.enum(["shared", "revoked", "auto_revoked"]).optional(), startAt: z.date().optional(), endAt: z.date().optional() }).refine(input => !input.startAt || !input.endAt || input.startAt <= input.endAt, { message: "Start date must be before end date." }).optional()).query(({ ctx, input }) => getAdminComparisonSharingAuditSummary(ctx.user.id, input)),
    exportAdminComparisonSharingAudit: adminProcedure.input(z.object({ ownerId: z.number().int().positive().optional(), action: z.enum(["shared", "revoked", "auto_revoked"]).optional(), startAt: z.date().optional(), endAt: z.date().optional() }).refine(input => !input.startAt || !input.endAt || input.startAt <= input.endAt, { message: "Start date must be before end date." }).optional()).mutation(({ ctx, input }) => createAdminComparisonSharingAuditExport(ctx.user.id, input)),
    adminComparisonSharingAuditExports: adminProcedure.input(z.object({ archived: z.boolean().optional(), status: z.enum(["queued", "ready", "failed"]).optional(), startAt: z.date().optional(), endAt: z.date().optional() }).refine(input => !input.startAt || !input.endAt || input.startAt <= input.endAt, { message: "Start date must be before end date." }).optional()).query(({ ctx, input }) => listAdminComparisonSharingAuditExports(ctx.user.id, input)),
    setAdminComparisonSharingAuditExportArchived: adminProcedure.input(z.object({ exportId: z.number().int().positive(), archived: z.boolean() })).mutation(({ ctx, input }) => setAdminComparisonSharingAuditExportArchived(ctx.user.id, input.exportId, input.archived)),
    comparisonSharingExportRetention: adminProcedure.query(({ ctx }) => getComparisonSharingExportRetentionPolicy(ctx.user.id)),
    updateComparisonSharingExportRetention: adminProcedure.input(z.object({ enabled: z.boolean(), retentionDays: z.union([z.literal(30), z.literal(60), z.literal(90), z.literal(180), z.literal(365)]) })).mutation(({ ctx, input }) => updateComparisonSharingExportRetentionPolicy(ctx.user.id, input, parseCookie(ctx.req.headers.cookie ?? "")[COOKIE_NAME] ?? "")),
    comparisonSharingExportRetentionRuns: adminProcedure.query(({ ctx }) => listComparisonSharingExportRetentionRuns(ctx.user.id)),
    monthlyCertificateAuditReportSchedule: adminProcedure.query(({ ctx }) => getMonthlyCertificateAuditReportSchedule(ctx.user.id)),
    updateMonthlyCertificateAuditReportSchedule: adminProcedure.input(z.object({ enabled: z.boolean(), recipientIds: z.array(z.number().int().positive()).max(100) })).mutation(({ ctx, input }) => updateMonthlyCertificateAuditReportSchedule(ctx.user.id, input, parseCookie(ctx.req.headers.cookie ?? "")[COOKIE_NAME] ?? "")),
    monthlyComparisonReviewSchedule: adminProcedure.query(({ ctx }) => getMonthlyComparisonReviewSchedule(ctx.user.id)),
    updateMonthlyComparisonReviewSchedule: adminProcedure.input(z.object({ enabled: z.boolean(), recipientIds: z.array(z.number().int().positive()).max(100), expiryWarningDays: z.number().int().min(1).max(90) })).mutation(({ ctx, input }) => updateMonthlyComparisonReviewSchedule(ctx.user.id, input, parseCookie(ctx.req.headers.cookie ?? "")[COOKIE_NAME] ?? "")),
    analytics: adminProcedure.query(({ ctx }) => getSchoolAnalytics(ctx.user.id)),
    interventionAnalytics: adminProcedure.input(interventionAnalyticsInput.optional()).query(({ ctx, input }) => getSchoolInterventionAnalytics(ctx.user.id, input)),
    exportInterventionAnalytics: adminProcedure.input(interventionAnalyticsInput.optional()).mutation(({ ctx, input }) => createSchoolInterventionExport(ctx.user.id, input)),
  }),
  courses: router({
    list: protectedProcedure.query(({ ctx }) => listCoursesForUser(ctx.user.id)),
    detail: protectedProcedure.input(z.object({ courseId: z.number().int().positive() })).query(({ ctx, input }) => getCourseDetail(ctx.user.id, input.courseId)),
    create: teacherProcedure.input(z.object({ code: z.string().min(2).max(32), title: z.string().min(2).max(180), subject: z.string().min(2).max(120).optional(), classSection: z.string().min(2).max(120).optional(), description: z.string().max(4000).optional() })).mutation(({ ctx, input }) => createCourse(ctx.user.id, input)),
    publish: teacherProcedure.input(z.object({ courseId: z.number().int().positive() })).mutation(({ ctx, input }) => publishCourse(ctx.user.id, input.courseId)),
    enroll: teacherProcedure.input(z.object({ courseId: z.number().int().positive(), studentId: z.number().int().positive() })).mutation(({ ctx, input }) => enrollStudent(ctx.user.id, input.courseId, input.studentId)),
    createModule: teacherProcedure.input(z.object({ courseId: z.number().int().positive(), title: z.string().min(2).max(180), position: z.number().int().min(0) })).mutation(({ ctx, input }) => createModule(ctx.user.id, input)),
    createLesson: teacherProcedure.input(z.object({ moduleId: z.number().int().positive(), title: z.string().min(2).max(180), content: z.string().max(16000).optional(), videoUrl: z.string().url().optional(), resourceUrl: z.string().url().optional(), durationMinutes: z.number().int().min(0).max(1440), position: z.number().int().min(0), publish: z.boolean() })).mutation(({ ctx, input }) => createLesson(ctx.user.id, input)),
    progress: protectedProcedure.input(z.object({ lessonId: z.number().int().positive(), resumeSecond: z.number().int().min(0), completed: z.boolean() })).mutation(({ ctx, input }) => setLessonProgress(ctx.user.id, input.lessonId, input.resumeSecond, input.completed)),
  }),
  assignments: router({
    list: protectedProcedure.query(({ ctx }) => listAssignments(ctx.user.id)),
    create: teacherProcedure.input(z.object({ courseId: z.number().int().positive(), title: z.string().min(2).max(180), instructions: z.string().min(5).max(8000), dueAt: z.date().optional(), maxPoints: z.number().int().min(1).max(1000), publish: z.boolean() })).mutation(({ ctx, input }) => createAssignment(ctx.user.id, input)),
    submit: protectedProcedure.input(z.object({ assignmentId: z.number().int().positive(), body: z.string().min(1).max(12000), attachmentUrl: z.string().max(2048).optional() })).mutation(({ ctx, input }) => submitAssignment(ctx.user.id, input.assignmentId, input.body, input.attachmentUrl)),
    grade: teacherProcedure.input(z.object({ submissionId: z.number().int().positive(), score: z.number().int().min(0).max(1000), feedback: z.string().max(8000) })).mutation(({ ctx, input }) => gradeSubmission(ctx.user.id, input.submissionId, input.score, input.feedback)),
    submissions: teacherProcedure.input(z.object({ courseId: z.number().int().positive() })).query(({ ctx, input }) => listSubmissionsForTeacher(ctx.user.id, input.courseId)),
  }),
  assessments: router({
    list: protectedProcedure.query(({ ctx }) => listExams(ctx.user.id)),
    results: protectedProcedure.query(({ ctx }) => listMyAssessmentResults(ctx.user.id)),
    attempts: teacherProcedure.query(({ ctx }) => listAssessmentAttemptsForReview(ctx.user.id)),
    detail: protectedProcedure.input(z.object({ examId: z.number().int().positive() })).query(({ ctx, input }) => getExamForAttempt(ctx.user.id, input.examId)),
    create: teacherProcedure.input(z.object({ courseId: z.number().int().positive(), title: z.string().min(2).max(180), description: z.string().max(4000).optional(), durationMinutes: z.number().int().min(1).max(720), publish: z.boolean() })).mutation(({ ctx, input }) => createExam(ctx.user.id, input)),
    addQuestion: teacherProcedure.input(z.object({ examId: z.number().int().positive(), prompt: z.string().min(2).max(4000), options: z.array(z.string().min(1).max(1000)).min(2).max(8), answerKey: z.string().min(1).max(1000), points: z.number().int().min(1).max(1000), position: z.number().int().min(0) })).mutation(({ ctx, input }) => addExamQuestion(ctx.user.id, input)),
    submit: protectedProcedure.input(z.object({ examId: z.number().int().positive(), answers: z.record(z.string(), z.string()) })).mutation(({ ctx, input }) => submitExamAttempt(ctx.user.id, input.examId, input.answers)),
    review: teacherProcedure.input(z.object({ attemptId: z.number().int().positive(), feedback: z.string().min(2).max(4000) })).mutation(({ ctx, input }) => reviewAssessmentAttempt(ctx.user.id, input.attemptId, input.feedback)),
  }),
  mistakes: router({
    list: protectedProcedure.query(({ ctx }) => listMistakes(ctx.user.id)),
    save: protectedProcedure.input(z.object({ id: z.number().int().positive().optional(), courseId: z.number().int().positive().optional(), topic: z.string().min(2).max(180), reflection: z.string().min(5).max(4000), nextStep: z.string().max(4000).optional(), resolved: z.boolean().optional() })).mutation(({ ctx, input }) => saveMistake(ctx.user.id, input)),
  }),
  schedule: router({
    list: protectedProcedure.query(({ ctx }) => listSchedule(ctx.user.id)),
    create: protectedProcedure.input(z.object({ title: z.string().min(2).max(180), startsAt: z.date(), endsAt: z.date(), location: z.string().max(200).optional(), courseId: z.number().int().positive().optional(), audience: z.enum(["school", "course", "personal"]) })).mutation(({ ctx, input }) => createScheduleEvent(ctx.user.id, input)),
  }),
  governance: router({
    requestBackup: adminProcedure.mutation(({ ctx }) => createBackupJob(ctx.user.id)),
    backups: adminProcedure.query(({ ctx }) => listBackupJobs(ctx.user.id)),
    requestExport: adminProcedure.input(z.object({ type: z.enum(["course", "user", "performance", "system"]), filterSnapshot: z.record(z.string(), z.unknown()).default({}) })).mutation(({ ctx, input }) => requestReportExport(ctx.user.id, input.type, input.filterSnapshot)),
    exports: adminProcedure.query(({ ctx }) => listReportExports(ctx.user.id)),
  }),
  communications: router({
    list: protectedProcedure.query(({ ctx }) => listConversations(ctx.user.id)),
    create: protectedProcedure.input(z.object({ subject: z.string().min(2).max(180), participantIds: z.array(z.number().int().positive()).min(1).max(30) })).mutation(({ ctx, input }) => createConversation(ctx.user.id, input)),
    messages: protectedProcedure.input(z.object({ conversationId: z.number().int().positive() })).query(({ ctx, input }) => listMessages(ctx.user.id, input.conversationId)),
    send: protectedProcedure.input(z.object({ conversationId: z.number().int().positive(), body: z.string().min(1).max(8000) })).mutation(({ ctx, input }) => sendMessage(ctx.user.id, input.conversationId, input.body)),
  }),
  notifications: router({
    list: protectedProcedure.query(({ ctx }) => listNotifications(ctx.user.id)),
    inbox: protectedProcedure.query(({ ctx }) => getNotificationInbox(ctx.user.id)),
    preferences: protectedProcedure.query(({ ctx }) => getNotificationPreferences(ctx.user.id)),
    updatePreferences: protectedProcedure.input(z.object({ staffUpdatesEnabled: z.boolean(), gradeUpdatesEnabled: z.boolean(), assessmentUpdatesEnabled: z.boolean(), learningRemindersEnabled: z.boolean(), emailDeliveryEnabled: z.boolean(), pushDeliveryEnabled: z.boolean(), reminderEnabled: z.boolean(), reminderTimeUtc: z.string().regex(/^([01]\d|2[0-3]):[0-5]\d$/, "Choose a valid local time."), reminderTimezone: z.string().min(1).max(64).refine(timezone => { try { new Intl.DateTimeFormat("en-US", { timeZone: timezone }).format(); return true; } catch { return false; } }, "Choose a valid IANA timezone."), reminderWeekdaysOnly: z.boolean() })).mutation(({ ctx, input }) => updateNotificationPreferences(ctx.user.id, input, parseCookie(ctx.req.headers.cookie ?? "")[COOKIE_NAME] ?? "")),
    sent: teacherProcedure.query(({ ctx }) => listSentNotifications(ctx.user.id)),
    markRead: protectedProcedure.input(z.object({ notificationId: z.number().int().positive() })).mutation(({ ctx, input }) => markNotificationRead(ctx.user.id, input.notificationId)),
    create: teacherProcedure.input(z.object({ recipientId: z.number().int().positive(), title: z.string().min(2).max(180), body: z.string().min(2).max(4000), href: z.string().max(500).optional() })).mutation(({ ctx, input }) => createNotification(ctx.user.id, input)),
  }),
  ai: router({
    request: protectedProcedure.input(z.object({ feature: z.enum(["study_plan", "feedback_draft", "career_guidance"]), inputSummary: z.string().min(5).max(4000) })).mutation(({ ctx, input }) => createAiRun(ctx.user.id, input.feature, input.inputSummary)),
    studyPlan: protectedProcedure.input(z.object({ learningContext: z.string().min(10).max(4000) })).mutation(({ ctx, input }) => generateStudyPlan(ctx.user.id, input.learningContext)),
    history: protectedProcedure.query(({ ctx }) => listMyAcceptedAiRuns(ctx.user.id)),
    pending: adminProcedure.query(({ ctx }) => listPendingAiRuns(ctx.user.id)),
    review: adminProcedure.input(z.object({ runId: z.number().int().positive(), decision: z.enum(["accepted", "rejected"]) })).mutation(({ ctx, input }) => reviewAiRun(ctx.user.id, input.runId, input.decision)),
  }),
});

export type AppRouter = typeof appRouter;
